### ISSUE TITLE
Nightly update 12-9 failed: HDF5 error 

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#150]
hisparc-update failed:

`/var/log/hisparc-update.log:`
```
2016-09-13 04:05:49,420 - INFO - [11674] - Processing events and storing ESD for Summary: 1005 - 12 Sep 2016
2016-09-13 04:05:54,806 - INFO - [11675] - Processing events and storing ESD for Summary: 1003 - 12 Sep 2016
2016-09-13 04:05:54,947 - INFO - [11675] - Processing events and storing ESD for Summary: 1001 - 12 Sep 2016
2016-09-13 04:05:54,947 - ERROR - [11603] - Exception occured.
Traceback (most recent call last):
  File "/srv/publicdb/www/scripts/hisparc-update.py", line 44, in <module>
    run()
  File "/srv/publicdb/www/scripts/hisparc-update.py", line 27, in run
    completed = hg.jobs.update_all_histograms()
  File "/srv/publicdb/www/scripts/../django_publicdb/histograms/jobs.py", line 177, in update_all_histograms
    perform_update_tasks()
  File "/srv/publicdb/www/scripts/../django_publicdb/histograms/jobs.py", line 198, in perform_update_tasks
    update_esd()
  File "/srv/publicdb/www/scripts/../django_publicdb/histograms/jobs.py", line 235, in update_esd
    for summary, tmp_locations in results:
  File "/srv/publicdb/publicdb_env/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 604, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1085, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 294, in H5F_super_read
    unable to load superblock
  File "H5AC.c", line 1320, in H5AC_protect
    H5C_protect() failed.
  File "H5C.c", line 3574, in H5C_protect
    can't load entry
  File "H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "H5Fsuper_cache.c", line 476, in H5F_sblock_load
    truncated file: eof = 2965724256, sblock->base_addr = 0, stored_eoa = 2965740640

End of HDF5 error back trace

Unable to open/create file '/databases/frome/2016/9/2016_9_12.h5'

```

I retried, with same failure. 

I turned off multiprocessing and restarted again. (`uppub && uphis`)

**Comment by 153957** [comment]
Same/similar error happened last week (night of 6-7 sept). Restarted without problems that time.
Could be caused by stations uploading yesterdays data while update is running.

**Comment by tomkooij** [comment]
Ok. Thanks!

**Comment by tomkooij** [comment]
```
2016-09-13 10:48:06,507 - INFO - [17841] - Finished building histograms
2016-09-13 10:48:06,507 - INFO - [17841] - Done.
```

multipressing set to `True` again and restarted. 

Closing.
