### ISSUE TITLE
Raw data download does not work

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#199]
Reported by @davidfokkema.

Using SAPPHiRE to download raw (non-ESD) data using the XMLRPC protocol results in an error:

```python
import tables
from datetime import datetime
from sapphire import publicdb
data = tables.open_file('data.h5', 'w')
publicdb.download_data(data, '/s599', 599, datetime(2018, 1, 16), datetime(2018, 1, 17), get_blobs=True)
```
results in
```
Traceback (most recent call last):
  File "<ipython-input-6-aa6e75210ea6>", line 1, in <module>
    publicdb.download_data(data, '/s599', 599, datetime(2018, 1, 16), datetime(2018, 1, 17), get_blobs=True)
  File "/Users/david/work/HiSPARC/software/sapphire/sapphire/publicdb.py", line 65, in download_data
    url = server.hisparc.get_data_url(station_id, t0, get_blobs)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
ProtocolError: <ProtocolError for data.hisparc.nl/raw_data/rpc: 403 Forbidden>
```

The result in the uwsgi log is:
```
POST /raw_data/rpc => generated 1374 bytes in 3 msecs (HTTP/1.1 403) 1 headers in 51 bytes (1 switches on core 0)
```

**Comment by tomkooij** [comment]
This is probably a config thing on `pique` / django.

I can visit `data.hisparc.nl/raw_data/rpc` using a browser. This is results in a normal reply.

I get `403 Forbidden` when using python xmlrpc. I'm guessing Django is doing some fancy user-agent(?)  based blocking.

I would test passing a fake user-agent, if I knew how :-)


```python
>>> server = ServerProxy(sapphire.publicdb.PUBLICDB_XMLRPC_URL, verbose=True)
>>> server.hisparc.get_url()
send: b'POST /raw_data/rpc HTTP/1.1\r\nHost: data.hisparc.nl\r\nAccept-Encoding: gzip\r\nContent-Type: text/xml\r\nUser-Agent: Python-xmlrpc/3.6\r\nContent-Length: 109\r\n\r\n'
send: b"<?xml version='1.0'?>\n<methodCall>\n<methodName>hisparc.get_url</methodName>\n<params>\n</params>\n</methodCall>\n"
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Content-Type ---------------------------------------------------------------------------

[knip]

ProtocolError: <ProtocolError for data.hisparc.nl/raw_data/rpc: 403 Forbidden>
```

**Comment by tomkooij** [comment]
This fix is already "live" on pique. Raw data downloading is working again.

**Comment by davidfokkema** [comment]
Yes, wonderful, thanks!
