### ISSUE TITLE
Public database code cannot be tested in isolation

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/publicdb#218]
I built a publicdb VM, created some fake stations (with actual station numbers to match reality), downloaded actual data, and built histograms. Unfortunately, that fails. Behind the scenes, the publicdb histogram code calls sapphire, which uses the API to call http://data.hisparc.nl/ thus breaking out of the VM. Since the fake clusters didn't match to the actual clusters, an error resulted. I don't really care about the error, but all publicdb VM code should stay within the VM and should certainly *not* call any production server. I'm unsure how to solve this cleanly. Any ideas appreciated. I understand the not-very-high priority, but we presently don't really have a development / staging environment.

**Comment by 153957** [comment]
We should simply use a configurable API base url for the SAPPHiRE API in the publicdb, which can be configured in the settings.

**Comment by 153957** [comment]
Similar for the Nagios status checks, the base url should also be configurable:
https://github.com/HiSPARC/publicdb/blob/master/publicdb/status_display/nagios.py#L71
Or at least allow the option to disable them.

**Comment by davidfokkema** [comment]
Yes, hardcoded URLs are a no-no. While it is easy to configure things in the Django settings file, the problem is within SAPPHiRE. The publicdb code calls the SAPPHiRE code which calls the API. This happens quite deep within the code, resulting in a long traceback:
```python
Traceback (most recent call last):
  File "scripts/hisparc-update.py", line 44, in <module>
    run()
  File "scripts/hisparc-update.py", line 27, in run
    completed = update_all_histograms()
  File "scripts/../publicdb/histograms/jobs.py", line 186, in update_all_histograms
    perform_update_tasks()
  File "scripts/../publicdb/histograms/jobs.py", line 209, in perform_update_tasks
    update_histograms()
  File "scripts/../publicdb/histograms/jobs.py", line 323, in update_histograms
    perform_coincidences_tasks)
  File "scripts/../publicdb/histograms/jobs.py", line 353, in perform_tasks_manager
    results = map(perform_certain_tasks, summaries)
  File "scripts/../publicdb/histograms/jobs.py", line 439, in perform_coincidences_tasks
    update_station_timing_offsets(network_summary)
  File "scripts/../publicdb/histograms/jobs.py", line 632, in update_station_timing_offsets
    network_off = esd.DetermineStationTimingOffsetsESD(stations)
  File "/srv/publicdb/publicdb_venv/lib/python2.7/site-packages/sapphire/analysis/calibration.py", line 126, in __init__
    force_stale=self.force_stale)
  File "/srv/publicdb/publicdb_venv/lib/python2.7/site-packages/sapphire/clusters.py", line 866, in __init__
    self.set_center_off_mass_at_origin()
  File "/srv/publicdb/publicdb_venv/lib/python2.7/site-packages/sapphire/clusters.py", line 475, in set_center_off_mass_at_origin
    x, y, z = self.calc_center_of_mass_coordinates()
  File "/srv/publicdb/publicdb_venv/lib/python2.7/site-packages/sapphire/clusters.py", line 597, in calc_center_of_mass_coordinates
    for station in self.stations
TypeError: 'NoneType' object is not iterable
```
Somewhere the API is called, returning `None` for the stations making up the fake cluster, I guess.

**Comment by 153957** [comment]
Ok, so maybe in SAPPHiRE we should use os.environ in the API object (with the current values as fallback) to be able to easily configure the base url there..

**Comment by tomkooij** [comment]
+1 

(but low prio)

**Comment by 153957** [comment]
Should be fixed now.
