### ISSUE TITLE
RuntimeError in daily `hisparc-update`

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#246]
```
INFO:publicdb.histograms.jobs:Updating coincidence histograms for Network Summary: 01 Jan 2019
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/publicdb/publicdb_venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/publicdb/publicdb_venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/publicdb/publicdb_venv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/publicdb/publicdb_venv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/publicdb/www/publicdb/histograms/management/commands/updatehistograms.py", line 23, in handle
    completed = update_all_histograms()
  File "/srv/publicdb/www/publicdb/histograms/jobs.py", line 61, in update_all_histograms
    perform_update_tasks()
  File "/srv/publicdb/www/publicdb/histograms/jobs.py", line 84, in perform_update_tasks
    update_histograms()
  File "/srv/publicdb/www/publicdb/histograms/jobs.py", line 199, in update_histograms
    perform_tasks_manager(NetworkSummary, "needs_update_coincidences", perform_coincidences_tasks)
  File "/srv/publicdb/www/publicdb/histograms/jobs.py", line 226, in perform_tasks_manager
    for summary, tmp_locations in results:
  File "/srv/publicdb/publicdb_venv/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
Exception: Couldn't get requested data from server nor find it locally.
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

Fortunately this is a traceable `RuntimeError` from `sapphire.api`: https://github.com/HiSPARC/sapphire/blob/3bc55de2c767011f62ad6d1c99e959043fe6df74/sapphire/api.py#L139

I'll solve this on some monday

**Comment by 153957** [comment]
Not seen recently. Might have been an issue with reaching the server. Should appear again in Sentry if it happens again.
