### ISSUE TITLE
Django 1.6 - MySQL server has gone away

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#78]
I updated Django to 1.6 yesterday and no histograms are available for today.. uh-oh
This error is in the `hisparc-update.log`:

```
2015-01-16 04:00:59,345 - INFO - [19153] - Update check finished.
2015-01-16 04:00:59,345 - INFO - [19153] - Building new histograms...
2015-01-16 04:00:59,452 - INFO - [19254] - Processing events and storing ESD for Summary: 20003 - 15 Jan 2015
2015-01-16 04:00:59,536 - INFO - [19256] - Processing events and storing ESD for Summary: 14001 - 15 Jan 2015
2015-01-16 04:00:59,537 - INFO - [19255] - Processing events and storing ESD for Summary: 20002 - 15 Jan 2015
2015-01-16 04:00:59,553 - INFO - [19257] - Processing events and storing ESD for Summary: 13201 - 15 Jan 2015
2015-01-16 04:01:21,274 - WARNING - [19257] - /srv/publicdb/publicdb_env/lib/python2.7/site-packages/sapphire/analysis/find_mpv.py:75: UserWarning: Fit failed
  warnings.warn("Fit failed")

2015-01-16 04:01:22,388 - INFO - [19257] - Processing events and storing ESD for Summary: 13006 - 15 Jan 2015
2015-01-16 04:01:22,425 - ERROR - [19153] - Exception occured.
Traceback (most recent call last):
  File "/srv/publicdb/www/scripts/hisparc-update.py", line 42, in <module>
    run()
  File "/srv/publicdb/www/scripts/hisparc-update.py", line 25, in run
    completed = hg.jobs.update_all_histograms()
  File "/srv/publicdb/www/scripts/../django_publicdb/histograms/jobs.py", line 174, in update_all_histograms
    state.save()
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/django/db/models/base.py", line 570, in save_base
    with transaction.commit_on_success_unless_managed(using=using, savepoint=False):
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/django/db/transaction.py", line 280, in __enter__
    connection.set_autocommit(False)
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/django/db/backends/__init__.py", line 340, in set_autocommit
    self._set_autocommit(autocommit)
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
OperationalError: (2006, 'MySQL server has gone away')
(END) 
```

Possibly related:
- https://docs.djangoproject.com/en/1.6/releases/1.6/#new-transaction-management-model
- https://code.djangoproject.com/ticket/21597#comment:29

So probably just need to close the connection before the save to ensure it makes a new fresh connection..

**Comment by davidfokkema** [comment]
That's a pain.

**Comment by 153957** [comment]
Might be fixed now, though there might still be some places where this error might occur..
Kind of annoying that this can happen..

**Comment by 153957** [comment]
This error has not occured again, probably fixed.
